
package com.act.ws.localhost.monitorwebservice.monitorcommand_wsdl;

import com.act.ws.ObjectFactory;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;



/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MonitorPortType", targetNamespace = "http://localhost//MonitorWebservice/monitorCommand?wsdl")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MonitorPortType {


    /**
     * Service definition of function ns__monitorCommand
     * 
     * @param monitorCommand
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "monitorCommand", targetNamespace = "urn:monitor", className = "monitor.MonitorCommand")
    @ResponseWrapper(localName = "monitorCommandResponse", targetNamespace = "urn:monitor", className = "monitor.MonitorCommandResponse")
    public String monitorCommand(
		    @WebParam(name = "monitorCommand", targetNamespace = "")
				    String monitorCommand);

}
